#!/usr/bin/env bash
# Bash script that installs nginx, set to listening on port 80 and return a page while using curl.

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'nginx full'

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx reload
