#!/usr/bin/env bash
# Bash script that installs nginx, set to listening on port 80 and return a page while using curl.

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx reload
