#!/usr/bin/env bash
# Bash script that installs nginx, set to listening on port 80 and return a page while using curl.

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
