#!/usr/bin/env bash
# Bash script that configures your Nginx server so that /redirect_me is redirecting to another page.

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
