#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

CONFIGURATION="
frontend http_front
	bind *:80
	stats uri /haproxy?stats
	default_backend http_back

backend http_back
	balance roundrobin
	server 3388-web-01 34.139.188.96:80 check
	server 3388-web-02 54.209.148.200:80 check
"

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get update -y
apt-get install haproxy=2.5.\* -y
echo "$CONFIGURATION" >> /etc/haproxy/haproxy.cfg
systemctl restart haproxy
