#!/usr/bin/env bash
# Fix server to listening on port 80 of all the server’s active IPv4 IPs.

service nginx start
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -s reload
service nginx restart
