#!/usr/bin/env bash
# Fix server to listening on port 80 of all the server’s active IPv4 IPs.

sed -i "17 s/listen .*/listen 80 default_server;/" default
sudo nginx -s reload
sudo service nginx restart
