#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,
# but for the 9th iteration, displays Best School 
# and then Hi on a new line.
i=0
while [ $i -lt 11 ]
do
	if [ $i = 9 ]; then
		echo "Hi"
		i=$((i + 1))
	else
		echo "Best School"
		i=$((i + 1))
	fi
done
