#!/usr/bin/env bash
# This script loops from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
i=1
while [ $i -lt 21 ]
do
	case $i in
		4)
			echo "4"
			echo "bad luck from China"
			i=$((i + 1))
			;;

		9)
			echo "9"
			echo "bad luck from Japan"
			i=$((i + 1))
			;;
		
		17)
			echo "17"
			echo "bad luck from Italy"
			i=$((i + 1))
			;;
	esac
	echo $i
	i=$((i + 1))
done
