#!/usr/bin/env bash
#This script gives you information about the school file.
#The Bash script should check if the file exists and print:
#if the file exists: school file exists
#if the file does not exist: school file does not exist
#If the file exists, print:
#if the file is empty: school file is empty
#if the file is not empty: school file is not empty
#if the file is a regular file: school is a regular file
#if the file is not a regular file: (nothing)
FILE=school
if test -f "$FILE"; then
	echo "$FILE exists"
	if test -s "$FILE"; then
		echo "$FILE is not empty"
	else
		echo "$FILE is empty"
	fi

	if test -f "$FILE"; then
		echo "$FILE is a regular file"
	fi
else
	echo "$FILE file does not exist"
fi
