#!/usr/bin/env bash
# Bash script that configures the container to run nginx as nginx user and nginx must be listening on all active IPs on port 8080.

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
chown - R nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-enabled/default

pkill apache2
sudo -u nginx service nginx restart
