#!/usr/bin/env bash
# Bash script that configures the container to run nginx as nginx user and nginx must be listening on all active IPs on port 8080.

sed -i '/user www-data;/c\user nginx;' /etc/nginx/nginx.conf
sed -i '/listen 80 default_server;/c\listen 8080 default_server;' /etc/nginx/sites-available/default
sudo service nginx restart
